"""Add AI missing columns

Revision ID: 149239b9b70f
Revises: a95fa4a67837
Create Date: 2026-07-12 05:09:14.765276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '149239b9b70f'
down_revision: Union[str, None] = 'a95fa4a67837'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_experience_technologies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('experience_id', sa.UUID(), nullable=False),
    sa.Column('technology_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['resume_experiences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technology_id'], ['technologies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resume_project_technologies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('technology_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['resume_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technology_id'], ['technologies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('resume_analysis', sa.Column('ats_score', sa.Integer(), nullable=True))
    op.add_column('resume_analysis', sa.Column('technical_score', sa.Integer(), nullable=True))
    op.add_column('resume_analysis', sa.Column('communication_score', sa.Integer(), nullable=True))
    op.add_column('resume_analysis', sa.Column('skill_gap', sa.JSON(), nullable=True))
    op.add_column('resume_analysis', sa.Column('missing_keywords', sa.JSON(), nullable=True))
    op.add_column('resume_analysis', sa.Column('learning_roadmap', sa.JSON(), nullable=True))
    op.add_column('resume_analysis', sa.Column('interview_readiness', sa.Text(), nullable=True))
    op.drop_column('resume_projects', 'technologies')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume_projects', sa.Column('technologies', sa.JSON(), nullable=True))
    op.drop_column('resume_analysis', 'interview_readiness')
    op.drop_column('resume_analysis', 'learning_roadmap')
    op.drop_column('resume_analysis', 'missing_keywords')
    op.drop_column('resume_analysis', 'skill_gap')
    op.drop_column('resume_analysis', 'communication_score')
    op.drop_column('resume_analysis', 'technical_score')
    op.drop_column('resume_analysis', 'ats_score')
    op.drop_table('resume_project_technologies')
    op.drop_table('resume_experience_technologies')
    # ### end Alembic commands ###
