"""normalize coding database

Revision ID: 9b409edfcb42
Revises: 149239b9b70f
Create Date: 2026-07-13 07:47:03.946206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b409edfcb42'
down_revision: Union[str, None] = '149239b9b70f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coding_hints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('problem_id', sa.UUID(), nullable=False),
    sa.Column('code_snapshot', sa.Text(), nullable=True),
    sa.Column('hint_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['coding_problems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coding_hints_problem_id'), 'coding_hints', ['problem_id'], unique=False)
    op.create_index(op.f('ix_coding_hints_user_id'), 'coding_hints', ['user_id'], unique=False)
    op.create_table('problem_companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('problem_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['coding_problems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problem_companies_problem_id'), 'problem_companies', ['problem_id'], unique=False)
    op.create_table('problem_tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('problem_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['coding_problems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problem_tags_problem_id'), 'problem_tags', ['problem_id'], unique=False)
    op.create_table('execution_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('stdout', sa.Text(), nullable=True),
    sa.Column('stderr', sa.Text(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('time_ms', sa.Integer(), nullable=True),
    sa.Column('memory_kb', sa.Integer(), nullable=True),
    sa.Column('pass_count', sa.Integer(), nullable=True),
    sa.Column('fail_count', sa.Integer(), nullable=True),
    sa.Column('total_cases', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['coding_submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id')
    )
    op.create_table('submission_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('correctness_score', sa.Integer(), nullable=True),
    sa.Column('code_quality_score', sa.Integer(), nullable=True),
    sa.Column('time_complexity', sa.String(length=100), nullable=True),
    sa.Column('space_complexity', sa.String(length=100), nullable=True),
    sa.Column('readability_feedback', sa.Text(), nullable=True),
    sa.Column('best_practices_feedback', sa.Text(), nullable=True),
    sa.Column('edge_case_feedback', sa.Text(), nullable=True),
    sa.Column('optimization_suggestions', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['coding_submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id')
    )
    op.drop_column('coding_problems', 'topics')
    op.drop_column('coding_problems', 'companies')
    op.drop_column('coding_submissions', 'execution_result')
    op.drop_column('coding_submissions', 'evaluation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coding_submissions', sa.Column('evaluation', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('coding_submissions', sa.Column('execution_result', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('coding_problems', sa.Column('companies', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('coding_problems', sa.Column('topics', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_table('submission_results')
    op.drop_table('execution_logs')
    op.drop_index(op.f('ix_problem_tags_problem_id'), table_name='problem_tags')
    op.drop_table('problem_tags')
    op.drop_index(op.f('ix_problem_companies_problem_id'), table_name='problem_companies')
    op.drop_table('problem_companies')
    op.drop_index(op.f('ix_coding_hints_user_id'), table_name='coding_hints')
    op.drop_index(op.f('ix_coding_hints_problem_id'), table_name='coding_hints')
    op.drop_table('coding_hints')
    # ### end Alembic commands ###
