from abc import ABC, abstractmethod
from typing import Optional

class BaseTextToSpeechProvider(ABC):
    """
    Abstract Base Class for Text-To-Speech (TTS) providers.
    Any future voice provider (e.g., ElevenLabs, Google TTS) must implement this interface.
    """
    
    @abstractmethod
    async def synthesize(self, text: str, voice_id: Optional[str] = None) -> bytes:
        """
        Synthesizes text into audio bytes.
        
        Args:
            text: The text generated by the AI Interviewer.
            voice_id: An optional string to specify the voice profile.
            
        Returns:
            The synthesized audio bytes (e.g., MP3 or WAV).
        """
        pass
